### ISSUE TITLE
Asn1 Object Getting Refreshed Automatically

### ISSUE THREAD

**Issue by amansem** [impratikjaiswal/amenitypj#4]
Steps to reproduce:  *BETA VERSION*
- Enter input data
- Select Input format and output format
- Select ASN1 Schema 
- Select ASN1 Object
- Now click on Submit it will give output but ASN1 Object list is getting refreshed and selected ASN1 Object is gone.

**Comment by impratikjaiswal** [comment]
Dear @amansem,

Thank you for your contribution in making of a better product !!!

Reported issue is fixed in "ASN1 Play v8.0.0 Amenity Pj v6.0.1".

Feel free to reopen the issue if needed.

Br
Pj
